version: 2
updates:
  # Check for Python dependencies updates
  - package-ecosystem: "pip"
    directory: "/"            # Location of your requirements.txt
    schedule:
      interval: "monthly"     # Check once a month
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"

  # Check for GitHub Actions version updates
  - package-ecosystem: "github-actions"
    directory: ".github/workflows" # Location of your workflow files
    schedule:
      interval: "monthly"          # Check once a month
    open-pull-requests-limit: 5
    commit-message:
      prefix: "actions"
